# Generated by Django 4.0.1 on 2022-03-13 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classname',
            fields=[
                ('classno', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('roll', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=40)),
                ('phone', models.CharField(default='', max_length=12)),
                ('parent_phone', models.CharField(default='', max_length=12)),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_management_system.classname')),
            ],
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_name', models.CharField(max_length=40)),
                ('ph_no', models.CharField(max_length=10)),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_management_system.classname')),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_attendance', models.IntegerField(default=0)),
                ('percent', models.IntegerField(default=0)),
                ('classname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_management_system.classname')),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance_management_system.faculty')),
                ('roll', models.ForeignKey(db_column='usn', on_delete=django.db.models.deletion.CASCADE, to='attendance_management_system.student')),
            ],
        ),
    ]
