# Generated by Django 4.0.1 on 2022-03-20 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management_system', '0002_attendance_attend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='roll',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='attend',
            field=models.ManyToManyField(blank=True, related_name='attendedstudent', to='attendance_management_system.Student'),
        ),
    ]
