# Generated by Django 4.0.1 on 2022-03-20 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management_system', '0003_remove_attendance_roll_alter_attendance_attend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='current_attendance',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='faculty',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='percent',
        ),
    ]
