# Generated by Django 4.0.1 on 2022-03-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management_system', '0004_remove_attendance_current_attendance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attend',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attend',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
