# Generated by Django 4.0.1 on 2022-03-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management_system', '0006_alter_attendance_attend'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='attendrecord',
            field=models.CharField(default=None, max_length=40),
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='attend',
        ),
        migrations.AddField(
            model_name='attendance',
            name='attend',
            field=models.ManyToManyField(blank=True, related_name='attendedstudent', to='attendance_management_system.Student'),
        ),
    ]
