# Generated by Django 4.0.1 on 2022-03-20 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management_system', '0007_attendance_attendrecord_remove_attendance_attend_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='classname',
        ),
    ]
