# Generated by Django 4.0.1 on 2022-03-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management_system', '0008_remove_attendance_classname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='attend',
        ),
        migrations.AddField(
            model_name='attendance',
            name='classname',
            field=models.CharField(default=None, max_length=40),
        ),
    ]
