# Generated by Django 4.0.1 on 2022-03-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management_system', '0009_remove_attendance_attend_attendance_classname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='classname',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
    ]
