# Generated by Django 4.0.1 on 2022-03-23 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management_system', '0012_alter_attendance_classname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='classname',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance_management_system.classname'),
        ),
    ]
