# Generated by Django 4.0.1 on 2022-03-24 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance_management_system', '0016_alter_attendance_classname'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=None),
        ),
    ]
